//first thread to generate a number every second, if the number is even, the second thread has to square the number 
// the third thread has to cube the number if it's an odd number
package Java;
import java.util.*;
public class Oddoreven implements Runnable {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Random random1 = new Random();
		Thread t1=new Thread();
		t1.start();
		int Number =random1.nextInt(1, 50);
		System.out.println("The number generated randomly is "+Number);
		
		Thread t2=new Thread();
		Thread t3=new Thread();
		if(Number%2==0) {
			t2.start();
			int s=Number*Number;
			System.out.println("The squared number generated by thread 2 is "+s);
		}
		else {
			t3.start();
			int c=Number*Number*Number;
			System.out.println("The cubed number generated by thread 3 is "+c);
		}
	}
	public void run() {
		new Oddoreven();
	}

}
